# Generated by Django 4.2.27 on 2026-08-01 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GenerationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem", models.TextField()),
                ("ac_code", models.TextField()),
                ("language", models.CharField(default="python", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Trong hàng chờ"),
                            ("worker", "Worker nhận việc"),
                            ("calling_api", "Gọi DeepSeek (JSON)"),
                            ("gen_script", "Nhận script Python"),
                            ("running_gen", "Chạy script sinh test"),
                            ("validating", "Chạy thử code AC"),
                            ("done", "Hoàn tất"),
                            ("need_rerun", "Chưa full — hỏi chạy lại"),
                            ("failed", "Lỗi"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("attempt", models.PositiveIntegerField(default=1)),
                ("gen_script", models.TextField(blank=True, default="")),
                ("testcases_json", models.TextField(blank=True, default="[]")),
                ("pass_count", models.PositiveIntegerField(default=0)),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("message", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
