# Generated by Django 4.2.27 on 2026-08-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationjob",
            name="ai_model",
            field=models.CharField(default="deepseek-chat", max_length=64),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="testcase_count",
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="generationjob",
            name="language",
            field=models.CharField(
                choices=[("python", "Python"), ("cpp", "C++")],
                default="python",
                max_length=16,
            ),
        ),
    ]
