# Generated by Django 4.2.27 on 2026-08-01 14:30

import dashboard.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0002_generationjob_ai_model_generationjob_testcase_count_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="generationjob",
            name="problem",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="JobImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to=dashboard.models.job_image_path)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="dashboard.generationjob",
                    ),
                ),
            ],
        ),
    ]
