# Generated by Django 4.2.27 on 2026-08-01 14:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_generationjob_problem_jobimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("language", models.CharField(default="python", max_length=16)),
                ("problem", models.TextField(blank=True, default="")),
                ("ac_code", models.TextField(blank=True, default="")),
                ("testcases_json", models.TextField(default="[]")),
                ("pass_count", models.PositiveIntegerField(default=0)),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stored_pools",
                        to="dashboard.generationjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
